# Automatically creates a minified json file when a json file is edited

name: Minify JSON
on:
  push:
    branches:
    - main
    paths:
    - '**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96

      - name: Create list of all changed json files
        id: json-list
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          files=""

          for file in "${ALL_CHANGED_FILES[@]}"; do
            case "$file" in *.json)
              files+="\"$file\","
              ;;
            esac
          done

          echo files="${files%,}" >> $GITHUB_OUTPUT

      - name: Minify JSON
        env:
          JSON_FILES: ${{ steps.json-list.outputs.files }}
        uses: Paradoxzyy/Minify-JSON-Action@1.3.0
        with:
          files: $JSON_FILES
          prefix: minified/

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[bot] auto-minify"
          push_options: "--force"
