name: Minify-JSON
on:
  push:
    branches:
    - main
    paths:
    - '**.json'
    - '!**/minified/*.json'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96

      - name: Create matrix of all changed json files
        id: matrix
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            case $file in *.json)
              echo "value=[{ \"path\": \"$file\", \"dirmin\": \"${file%/*}/minified/\", \"filename\": \"${file##*/}\" }]" >> $GITHUB_OUTPUT
              ;;
            esac
          done

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}

      - name: Create minified dir
        run: |
          if [ ! -d "${{ matrix.value.dirmin }}" ]; then
            mkdir -p "${{ matrix.value.dirmin }}"
          fi

      - name: Minify JSON
        uses: StefanEnsmann/Minify-JSON-Action@1.1.0
        with:
          input_file: "${{ matrix.value.path }}"
          output_file: "${{ matrix.value.dirmin }}${{ matrix.value.filename }}"

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[bot] auto-minify"
