name: Minify-JSON
on:
  push:
    branches:
    - main
    paths:
    - '**.json'
    - '!**/minified/*.json'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96

      - name: Create matrix
        id: matrix
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "value=[\"$file\"]" >> $GITHUB_OUTPUT
          done

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}

      - name: Split string to path & folder
        id: split
        env:
          FULLPATH: "${{ matrix.value }}"
        run: |
          echo "path=${FULLPATH%/*}" >> $GITHUB_OUTPUT
          echo "file=${FULLPATH##*/}" >> $GITHUB_OUTPUT

      - name: Create folder
        run: |
          if [ ! -d "${{ steps.split.outputs.path }}/minified" ]; then
            mkdir -p "${{ steps.split.outputs.path }}/minified"
            echo "created folder: ${{ steps.split.outputs.path }}"
          fi

      - name: Minify JSON
        uses: StefanEnsmann/Minify-JSON-Action@1.1.0
        with:
          input_file: "${{ matrix.value }}"
          output_file: ${{ steps.split.outputs.path }}/minified/${{ steps.split.outputs.file }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[bot] auto-minify"
