name: Deploy static content to Pages
on:
  workflow_dispatch:
  push:
    branches:
    - main

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # pre-deploy
  call-workflow-minify-json:
      permissions:
        contents: write
      uses: ./.github/workflows/minify-json.yml

  # deploy
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
